export enum KlineIndex {
	OPEN_TIME = 0,
	OPEN = 1,
	HIGH = 2,
	LOW = 3,
	CLOSE = 4,
	VOLUME = 5,
	CLOSE_TIME = 6,
	QUOTE_ASSET_VOLUME = 7,
	NUMBER_OF_TRADES = 8,
	TAKER_BUY_BASE_ASSET_VOLUME = 9,
	TAKER_BUY_QUOTE_ASSET_VOLUME = 10,
}
